name: 'spring-outbox-pattern'
services: 
  order-service:
    build:
     context: ../order-service
     dockerfile: Dockerfile
    container_name: order-service
    environment:
      - DB_URL=order-db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8081:8081"
    networks: [ "microservices"]
    depends_on: 
      - order-db

  order-poller:
    build:
      context: ../order-poller
      dockerfile: Dockerfile
    container_name: order-poller
    environment:
      - DB_URL=order-db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - KAFKA_URL=kafka
      - KAFKA_PORT=19092
    ports:
      - "8082:8082"
    networks: [ "microservices"]  
    depends_on:
      - order-db
      - zoo
      - kafka
 