server:
  port: 8082
  
spring:
  application:
    name: oauth-client-demo
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 565478090085-sllo4mrpqllndlvc2kem90sjjkgg4vsn.apps.googleusercontent.com
            clientSecret: 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
    user:
      name: dgarcia
      password:  12345678



logging:
  level:
    org.springframework.security: TRACE 
