server:
  port: 8082
  
spring:
  application:
    name: oauth-client-demo
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 
            clientSecret: 
      name: 
      password:  



logging:
  level:
    org.springframework.security: TRACE 
