server:
  port: 8082
  
spring:
  application:
    name: oauth-client-demo
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${clientId}
            clientSecret: ${clientSecret}
        
      name: dgarcia
      password:  12345678



logging:
  level:
    org.springframework.security: TRACE 
