server:
  port: 8082
  
spring:
  application:
    name: oauth-client-demo
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile  
    user:
      name: dgarcia
      password: 12345678



logging:
  level:
    org.springframework.security: TRACE 
