apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-service
  template:
    metadata:
      labels:
        app: combined-service
    spec:
      containers:
      - name: book-service
        image: manuonda/pattern-sidecar-book-service:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: log-volume
           mountPath: /logs
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
      - name: sidecar-service
        image: manuonda/pattern-sidecar-logging-service:4.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
         - name: log-volume
           mountPath: /logs
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports: 
          - containerPort: 8081
      volumes: 
        - name: log-volume
          emptyDir: {}
