apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  selector:
    app: combined-service
  ports:
    - name: book-service-port
      port: 80
      targetPort: 8080  # Para book-service
    - name: sidecar-service-port
      port: 81
      targetPort: 8081  # Para sidecar-service
