apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pv-claim # name of pvc essential for identifying the storage data
spec:
  resources:
    requests:
      storage: 1Gi  #this will tell kubernetes about the amount of space we are trying to claim
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce #This specifies the mode of the claim that we are trying to create.
