version: '3.8'

services:
  database:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
    volumes:
      - db-data:/var/lib/db
    networks:
      - springboot-mysql-network

  phpmyadmin:
    depends_on:
      database:
        condition: service_healthy
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - springboot-mysql-network

volumes:
  db-data: {}

networks:
  springboot-mysql-network:
    name: springboot-mysql-network
