server:
  port: 8085
spring:
  application:
    name: Spring Blog Application
  datasource :
    url: jdbc:mysql://localhost:3306/my_blog
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
      
  #flyway:

  # security:
  #  user:
  #     name: david
  #     password: david

app:
 jwt-secret: 66dd3673ee33b5ac40d660e2b8633b8a91cd04dbf6f7b68e5c9a41431f36ae53  #manuonda
 expiration-time: 809000




